### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by SOEST1** [CdriFry/C4_WS2NR#1]
Do I need to pay for the license after 30 days

**Comment by CdriFry** [comment]
Yes, I provide a driver that can be very accommodating, I develop other drivers that will gradually allow more "clean" work between the devices that we want to connect to control4 and those-here, this driver already allows a lot of things in the meantime, I spent a lot of time to develop it like any software and I work to add functions according to feedback, so I want to ask for a small compensation.
Once you are sure that everything works as you want, that your configuration works, you can think about buying a license for life, I will try to gradually add corrections but be aware that the driver has given you in the state. TEST before anything else.
The first 10-15 who will make returns or want a key, will be entitled to a key at a very special price.
Then contact me via mail or on discord tag @CaptainCalvie
